-- remove existing tables
alter table im_user_has_role drop constraint ref_im_user_id;
alter table im_user_has_role drop constraint ref_im_role_id;
drop table im_user if exists;
drop table im_role if exists;
drop table im_user_has_role if exists;
drop table im_id_table if exists;
-- create tables
create table im_user (id integer generated by default as identity (start with 1), olVersion integer not null, loginName varchar(255) not null, firstName varchar(255) not null, lastName varchar(255) not null, password varchar(255) not null, lastPasswordChange timestamp not null, primary key (id), unique (loginName));
create table im_role (id integer generated by default as identity (start with 1), olVersion integer not null, roleName varchar(255) not null, description varchar(4000), primary key (id), unique (roleName));
create table im_user_has_role (im_user_id integer not null, im_role_id integer not null, primary key (im_user_id, im_role_id));
create table im_id_table (nextId integer not null, unique (nextId));
alter table im_user_has_role add constraint ref_im_role_id foreign key (im_role_id) references im_role;
alter table im_user_has_role add constraint ref_im_user_id foreign key (im_user_id) references im_user;
-- initialize id table
insert into im_id_table(nextId) values(1);